# Generated by Django 5.2.16 on 2026-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='agent_links',
            field=models.JSONField(blank=True, default=list, verbose_name='代办/辅助申请链接'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/', verbose_name='APP 安装包'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='APP 版本号'),
        ),
        migrations.AddField(
            model_name='site',
            name='text_tutorials',
            field=models.JSONField(blank=True, default=list, verbose_name='文字教程链接'),
        ),
        migrations.AddField(
            model_name='site',
            name='video_tutorials',
            field=models.JSONField(blank=True, default=list, verbose_name='视频教程链接'),
        ),
    ]
