# Generated by Django 5.2.16 on 2026-08-04 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_site_agent_links_site_app_file_site_app_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name='平均评分(0-10)'),
        ),
        migrations.AddField(
            model_name='site',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评分人数'),
        ),
        migrations.AddField(
            model_name='site',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='访问次数'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='评分(0-10)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评论(可选)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='navigation.site', verbose_name='站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '站点评分',
                'verbose_name_plural': '站点评分',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('site', 'user'), name='unique_site_user_rating')],
            },
        ),
    ]
