# Generated by Django 5.2.16 on 2026-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_site_rating_avg_site_rating_count_site_visit_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title', models.CharField(default='探索好站', max_length=100, verbose_name='首页大标题')),
                ('home_subtitle', models.CharField(default='发现优质的金融与 Web3 工具', max_length=200, verbose_name='首页副标题')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
        migrations.AddField(
            model_name='site',
            name='app_download_url',
            field=models.URLField(blank=True, default='', verbose_name='APP 下载链接(原始)'),
        ),
    ]
