# Generated by Django 5.2.16 on 2026-08-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_appsetting_site_app_download_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='app_download_url',
        ),
        migrations.RemoveField(
            model_name='site',
            name='app_file',
        ),
        migrations.RemoveField(
            model_name='site',
            name='app_version',
        ),
        migrations.AddField(
            model_name='site',
            name='app_android_cached_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='安卓 APP 缓存时间'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_android_file',
            field=models.FileField(blank=True, null=True, upload_to='app_cache/', verbose_name='安卓 APP 本地缓存'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_android_size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='安卓 APP 缓存大小(字节)'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_android_url',
            field=models.URLField(blank=True, default='', verbose_name='安卓 APP 下载链接(原始)'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_ios_url',
            field=models.URLField(blank=True, default='', verbose_name='iOS App Store 链接'),
        ),
    ]
