# Generated by Django 5.2.16 on 2026-08-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_remove_site_app_download_url_remove_site_app_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='邀请码(可选)'),
        ),
    ]
