# Generated by Django 5.2.16 on 2026-08-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_site_invite_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('purpose', models.CharField(choices=[('register', '注册'), ('reset', '找回密码')], max_length=16, verbose_name='用途')),
                ('code_hash', models.CharField(max_length=64, verbose_name='验证码哈希(SHA-256)')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'constraints': [models.UniqueConstraint(fields=('email', 'purpose'), name='unique_email_purpose')],
            },
        ),
    ]
