# Generated by Django 5.2.16 on 2026-08-05 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_userfavorite_usersearchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='searched_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='搜索时间'),
        ),
    ]
