# Generated by Django 5.2.16 on 2026-08-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_alter_usersearchhistory_searched_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsetting',
            options={'verbose_name': '全局设置', 'verbose_name_plural': '全局设置'},
        ),
        migrations.AddField(
            model_name='appsetting',
            name='announcement',
            field=models.TextField(blank=True, default='', verbose_name='网站公告'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='announcement_enabled',
            field=models.BooleanField(default=False, verbose_name='显示公告'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='footer_copyright',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='底部版权信息'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='网站图标/Logo'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='SEO 描述'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SEO 关键词'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='SEO 标题'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='site_subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='网站副标题'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='site_title',
            field=models.CharField(default='FinNav', max_length=100, verbose_name='网站标题'),
        ),
    ]
