# Generated by Django 5.2.16 on 2026-08-05 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_alter_appsetting_options_appsetting_announcement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='invite_code',
        ),
        migrations.CreateModel(
            name='UserSiteInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(blank=True, default='', max_length=64, verbose_name='邀请码(可选)')),
                ('invite_link', models.URLField(blank=True, default='', verbose_name='邀请链接(可选)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invites', to='navigation.site', verbose_name='站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_invites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户站点邀请',
                'verbose_name_plural': '用户站点邀请',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'site'), name='unique_user_site_invite')],
            },
        ),
    ]
