# Generated by Django 5.2.16 on 2026-08-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_remove_site_invite_code_usersiteinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.FloatField(verbose_name='评分(0-5)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='rating_avg',
            field=models.FloatField(default=0.0, verbose_name='平均评分(0-5)'),
        ),
    ]
