# Generated by Django 5.2.16 on 2026-08-06 00:11

from django.db import migrations


def rescale_to_five(apps, schema_editor):
    """将历史 0-10 评分数据换算为 0-5 制（除以 2）。"""
    Rating = apps.get_model('navigation', 'Rating')
    Site = apps.get_model('navigation', 'Site')

    for rating in Rating.objects.all():
        rating.score = round(rating.score / 2, 1)
        rating.save(update_fields=['score'])

    for site in Site.objects.filter(rating_count__gt=0):
        site.rating_avg = round(site.rating_avg / 2, 1)
        site.save(update_fields=['rating_avg'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_alter_rating_score_alter_site_rating_avg'),
    ]

    operations = [
        migrations.RunPython(rescale_to_five, noop),
    ]