# Generated by Django 5.2.16 on 2026-08-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_rescale_rating_to_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='logo_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Logo 自动获取时间'),
        ),
    ]
