# Generated by Django 5.2.16 on 2026-08-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0014_site_logo_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后发送时间'),
        ),
    ]
