# Generated by Django 5.2.16 on 2026-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0015_emailverification_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='app_android_integrity_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='安卓 APP 完整性校验结果'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_android_sha256',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='安卓 APP 缓存 SHA-256'),
        ),
        migrations.AddField(
            model_name='site',
            name='app_android_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='安卓 APP 完整性最后校验时间'),
        ),
    ]
