# Generated by Django 5.2.16 on 2026-08-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0016_site_app_android_integrity_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='app_google_play_url',
            field=models.URLField(blank=True, default='', verbose_name='Google Play 链接'),
        ),
    ]
