# Generated by Django 5.2.16 on 2026-08-06 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0017_site_app_google_play_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='访问时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='navigation.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '站点访问记录',
                'verbose_name_plural': '站点访问记录',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='navigation__visited_351e92_idx'), models.Index(fields=['site', 'visited_at'], name='navigation__site_id_fbb456_idx')],
            },
        ),
    ]
