# Generated by Django 5.2.16 on 2026-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0019_tag_and_site_tags_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='令牌')),
                ('answer_hash', models.CharField(max_length=64, verbose_name='答案哈希(SHA-256)')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='尝试次数')),
                ('used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图形验证码',
                'verbose_name_plural': '图形验证码',
            },
        ),
        migrations.AddField(
            model_name='appsetting',
            name='head_scripts',
            field=models.TextField(blank=True, default='', verbose_name='前端 <head> 自定义脚本'),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='require_email_verification',
            field=models.BooleanField(default=True, verbose_name='注册需验证邮箱'),
        ),
    ]
