# Generated by Django 5.2.16 on 2026-08-07 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0020_captcha_appsetting_head_scripts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='twofa_enabled',
            field=models.BooleanField(default=False, verbose_name='启用双因素认证(2FA)'),
        ),
        migrations.AddField(
            model_name='site',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下载次数(本站分发)'),
        ),
        migrations.CreateModel(
            name='SiteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('url', models.URLField(verbose_name='网址')),
                ('description', models.TextField(blank=True, default='', verbose_name='站点描述(可选)')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submission', to='navigation.site', verbose_name='通过后创建的站点')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='navigation.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='submissions', to='navigation.tag', verbose_name='标签(可选)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '站点提交/审核',
                'verbose_name_plural': '站点提交/审核',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='令牌')),
                ('used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_challenges', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '2FA 挑战',
                'verbose_name_plural': '2FA 挑战',
            },
        ),
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, default='', max_length=64, verbose_name='TOTP 密钥(base32)')),
                ('enabled', models.BooleanField(default=False, verbose_name='是否启用')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '双因素认证',
                'verbose_name_plural': '双因素认证',
            },
        ),
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android_cache', '安卓(本站缓存)'), ('android_original', '安卓(原始链接)'), ('google_play', 'Google Play'), ('ios', 'iOS App Store')], max_length=24, verbose_name='平台/入口')),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下载时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='navigation.site', verbose_name='站点')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户(可选)')),
            ],
            options={
                'verbose_name': 'APP 下载记录',
                'verbose_name_plural': 'APP 下载记录',
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['downloaded_at'], name='navigation__downloa_fd0057_idx')],
            },
        ),
    ]
