# Generated by Django 5.2.16 on 2026-08-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0021_appsetting_twofa_enabled_site_download_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='sites_per_page',
            field=models.PositiveIntegerField(default=20, verbose_name='站点每页数量'),
        ),
    ]
