# Generated by Django 5.2.16 on 2026-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0022_appsetting_sites_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='invite_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='邀请码(可填)'),
        ),
        migrations.AddField(
            model_name='site',
            name='invite_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='邀请链接(可填)'),
        ),
    ]
