# Generated by Django 5.2.16 on 2026-08-09 00:47

from django.db import migrations, models

NEW_DEFAULTS = {
    'seo_title': 'FinNav',
    'seo_description': 'FinNav一个金融导航应用',
    'seo_keywords': '金融，银行，券商，web3',
    'announcement_enabled': True,
    'announcement': '欢迎来到FinNav！请自觉遵守相关法律法规，合法使用。',
    'footer_copyright': 'Copyright © 2026 FinNav.',
    'require_email_verification': False,
}


def apply_new_defaults(apps, schema_editor):
    AppSetting = apps.get_model('navigation', 'AppSetting')
    AppSetting.objects.filter(id=1).update(**NEW_DEFAULTS)


def revert_defaults(apps, schema_editor):
    AppSetting = apps.get_model('navigation', 'AppSetting')
    AppSetting.objects.filter(id=1).update(
        seo_title='',
        seo_description='',
        seo_keywords='',
        announcement_enabled=False,
        announcement='',
        footer_copyright='',
        require_email_verification=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0023_site_invite_code_site_invite_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='home_subtitle',
        ),
        migrations.RemoveField(
            model_name='appsetting',
            name='home_title',
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='announcement',
            field=models.TextField(blank=True, default='欢迎来到FinNav！请自觉遵守相关法律法规，合法使用。', help_text='展示在站点顶部；可支持换行与常见标点。', verbose_name='公告内容'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='announcement_enabled',
            field=models.BooleanField(default=True, verbose_name='显示公告'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='footer_copyright',
            field=models.CharField(blank=True, default='Copyright © 2026 FinNav.', help_text='显示在页面底部，例如「Copyright © 2026 FinNav.」。', max_length=200, verbose_name='底部版权信息'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='require_email_verification',
            field=models.BooleanField(default=False, help_text='开启后注册需邮件验证码确认邮箱真实性；关闭则填写邮箱+密码即可直接注册。', verbose_name='注册需验证邮箱'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='seo_description',
            field=models.CharField(blank=True, default='FinNav一个金融导航应用', help_text='搜索引擎结果页中的站点摘要，建议 50–150 字。', max_length=300, verbose_name='SEO 描述'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='seo_keywords',
            field=models.CharField(blank=True, default='金融，银行，券商，web3', help_text='用中英文逗号分隔多个关键词。', max_length=200, verbose_name='SEO 关键词'),
        ),
        migrations.AlterField(
            model_name='appsetting',
            name='seo_title',
            field=models.CharField(blank=True, default='FinNav', help_text='浏览器标签页与搜索引擎显示的标题；留空则使用网站标题。', max_length=120, verbose_name='SEO 标题'),
        ),
        migrations.RunPython(apply_new_defaults, revert_defaults),
    ]
