# Generated by Django 5.2.16 on 2026-08-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0024_remove_appsetting_home_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='share_base_url',
            field=models.CharField(blank=True, default='', help_text='如 https://finnav.app 或 http://192.168.1.70:8000（须为网页版前端可访问的地址，而非后端 API 地址）；填写后 App 分享的站点链接为「该地址/site/站点ID」，留空保持 finnav:///site/xx 格式。', max_length=200, verbose_name='转发来源域名/地址'),
        ),
    ]
