# Generated by Django 5.2.16 on 2026-08-18 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0025_appsetting_share_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLinkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', '安卓 APP'), ('google_play', 'Google Play'), ('ios', 'iOS App Store')], max_length=16, verbose_name='平台')),
                ('url', models.URLField(max_length=500, verbose_name='链接')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_link_submissions', to='navigation.site', verbose_name='站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_link_submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': 'APP 链接提交/审核',
                'verbose_name_plural': 'APP 链接提交/审核',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'site', 'platform'), name='unique_pending_app_link_submission')],
            },
        ),
        migrations.CreateModel(
            name='SiteTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', '文字教程'), ('video', '视频教程'), ('agent', '辅助/代办')], max_length=16, verbose_name='类型')),
                ('url', models.URLField(max_length=500, verbose_name='链接')),
                ('title', models.CharField(max_length=200, verbose_name='标题(自动获取)')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='访问量')),
                ('delete_pending', models.BooleanField(default=False, verbose_name='待管理员删除审核')),
                ('delete_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='删除申请时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorials', to='navigation.site', verbose_name='站点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_tutorials', to=settings.AUTH_USER_MODEL, verbose_name='分享者')),
            ],
            options={
                'verbose_name': '用户教程',
                'verbose_name_plural': '用户教程',
                'ordering': ['-view_count', '-created_at'],
                'indexes': [models.Index(fields=['site', 'type', 'view_count'], name='navigation__site_id_26c02a_idx'), models.Index(fields=['site', 'type', 'delete_pending'], name='navigation__site_id_812866_idx')],
            },
        ),
    ]
