# Generated by Django 5.2.16 on 2026-08-18 08:03

from django.conf import settings
from django.db import migrations, models


def backfill_existing_approved(apps, schema_editor):
    """存量教程在审核机制上线前已公开，回填为 approved。"""
    SiteTutorial = apps.get_model('navigation', 'SiteTutorial')
    SiteTutorial.objects.filter(status='pending').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0026_applinksubmission_sitetutorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetutorial',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='发布状态'),
        ),
        migrations.AddIndex(
            model_name='sitetutorial',
            index=models.Index(fields=['site', 'status', 'view_count'], name='navigation__site_id_a3685c_idx'),
        ),
        migrations.RunPython(backfill_existing_approved, migrations.RunPython.noop),
    ]
