# Generated by Django 5.2.16 on 2026-08-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0027_sitetutorial_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='agent_links',
        ),
        migrations.RemoveField(
            model_name='site',
            name='text_tutorials',
        ),
        migrations.RemoveField(
            model_name='site',
            name='video_tutorials',
        ),
    ]
