# Generated by Django 5.2.16 on 2026-08-19 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0028_remove_site_agent_links_remove_site_text_tutorials_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='规则代码')),
                ('name', models.CharField(max_length=50, verbose_name='规则名称')),
                ('points', models.IntegerField(default=0, verbose_name='积分值(可为负)')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('daily_limit', models.PositiveIntegerField(default=0, verbose_name='每日发放次数上限(0=不限)')),
                ('total_limit', models.PositiveIntegerField(default=0, verbose_name='累计发放次数上限(0=不限)')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '积分规则',
                'verbose_name_plural': '积分规则',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='emailverification',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='推广码(注册时可选)'),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='使用的推广码')),
                ('status', models.CharField(choices=[('qualified', '已达标'), ('revoked', '已作废')], default='qualified', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_invited_by', to=settings.AUTH_USER_MODEL, verbose_name='被邀请人')),
            ],
            options={
                'verbose_name': '邀请记录',
                'verbose_name_plural': '邀请记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, default='', max_length=12, unique=True, verbose_name='推广码')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='积分余额')),
                ('points_lifetime', models.PositiveIntegerField(default=0, verbose_name='累计获得积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='积分变动(可为负)')),
                ('balance_after', models.PositiveIntegerField(verbose_name='变动后余额')),
                ('ref_type', models.CharField(blank=True, choices=[('site_submission', '站点提交'), ('site_tutorial', '教程分享'), ('app_link_submission', 'APP 链接提交'), ('referral', '邀请推广'), ('manual', '管理员调整')], default='', max_length=32, verbose_name='来源类型')),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='来源对象ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='navigation.pointrule', verbose_name='规则')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='navigation__user_id_d9554b_idx'), models.Index(fields=['ref_type', 'ref_id'], name='navigation__ref_typ_fcd7ef_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ref_id__isnull', False)), fields=('user', 'rule', 'ref_type', 'ref_id'), name='unique_user_rule_ref')],
            },
        ),
    ]
