# Generated by Django 5.2.16 on 2026-08-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0030_seed_point_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='totpchallenge',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='校验失败次数'),
        ),
    ]
