# Generated by Django 5.2.16 on 2026-08-19 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0031_totpchallenge_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='ref_type',
            field=models.CharField(blank=True, choices=[('site_submission', '站点提交'), ('site_tutorial', '教程分享'), ('app_link_submission', 'APP 链接提交'), ('referral', '邀请推广'), ('experience_purchase', '经验购买'), ('experience_sale', '经验售卖'), ('manual', '管理员调整')], default='', max_length=32, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('excerpt', models.CharField(blank=True, default='', max_length=200, verbose_name='摘要(公开预览)')),
                ('content', models.TextField(verbose_name='正文(付费可见)')),
                ('price', models.PositiveIntegerField(default=10, verbose_name='价格(积分)')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可见(作者删除后隐藏)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='navigation.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '实战经验',
                'verbose_name_plural': '实战经验',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experiences/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='navigation.experience', verbose_name='经验')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_images', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '经验配图',
                'verbose_name_plural': '经验配图',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='navigation.experience', verbose_name='经验')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
            ],
            options={
                'verbose_name': '经验点赞',
                'verbose_name_plural': '经验点赞',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperiencePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='购买价格(积分快照)')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='navigation.experience', verbose_name='经验')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_purchases', to=settings.AUTH_USER_MODEL, verbose_name='购买者')),
            ],
            options={
                'verbose_name': '经验购买记录',
                'verbose_name_plural': '经验购买记录',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['site', 'is_active', '-created_at'], name='navigation__site_id_810434_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['site', '-sales_count'], name='navigation__site_id_77df22_idx'),
        ),
        migrations.AddConstraint(
            model_name='experiencelike',
            constraint=models.UniqueConstraint(fields=('experience', 'user'), name='unique_experience_user_like'),
        ),
        migrations.AddConstraint(
            model_name='experiencepurchase',
            constraint=models.UniqueConstraint(fields=('experience', 'user'), name='unique_experience_user_purchase'),
        ),
    ]
