# Generated by Django 5.2.16 on 2026-08-19 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0032_alter_pointtransaction_ref_type_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-like_count', '-created_at'], 'verbose_name': '实战经验', 'verbose_name_plural': '实战经验'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='excerpt',
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['site', 'is_active', '-like_count'], name='navigation__site_id_59c00b_idx'),
        ),
    ]
