# Generated by Django 5.2.16 on 2026-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0033_alter_experience_options_remove_experience_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='ref_type',
            field=models.CharField(blank=True, choices=[('site_submission', '站点提交'), ('site_tutorial', '教程分享'), ('app_link_submission', 'APP 链接提交'), ('referral', '邀请推广'), ('experience_purchase', '经验购买'), ('experience_sale', '经验售卖'), ('experience_edit_fee', '编辑经验扣费'), ('experience_delete_fee', '删除经验扣费'), ('manual', '管理员调整')], default='', max_length=32, verbose_name='来源类型'),
        ),
    ]
