# Generated by Django 5.2.16 on 2026-08-20

import secrets

from django.db import migrations

ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'


def _generate_code(UserProfile):
    for _ in range(50):
        code = ''.join(secrets.choice(ALPHABET) for _ in range(8))
        if not UserProfile.objects.filter(referral_code=code).exists():
            return code
    raise RuntimeError('无法生成唯一推广码')


def backfill_referral_codes(apps, schema_editor):
    """为历史遗留的空推广码资料回填唯一推广码，避免撞 unique 约束。"""
    UserProfile = apps.get_model('navigation', 'UserProfile')
    for profile in UserProfile.objects.filter(referral_code=''):
        profile.referral_code = _generate_code(UserProfile)
        profile.save(update_fields=['referral_code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0034_alter_pointtransaction_ref_type'),
    ]

    operations = [
        migrations.RunPython(backfill_referral_codes, noop),
    ]