# Generated by Django 5.2.16 on 2026-08-20 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0035_backfill_userprofile_referral_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='ref_type',
            field=models.CharField(blank=True, choices=[('site_submission', '站点提交'), ('site_tutorial', '教程分享'), ('app_link_submission', 'APP 链接提交'), ('referral', '邀请推广'), ('registration', '注册奖励'), ('experience_purchase', '经验购买'), ('experience_sale', '经验售卖'), ('experience_edit_fee', '编辑经验扣费'), ('experience_delete_fee', '删除经验扣费'), ('points_gift_out', '积分转赠(转出)'), ('points_gift_in', '积分转赠(收到)'), ('points_voucher_create', '兑换码生成'), ('points_voucher_redeem', '兑换码核销'), ('manual', '管理员调整')], default='', max_length=32, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='PointsGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='转赠积分')),
                ('message', models.CharField(blank=True, default='', max_length=200, verbose_name='留言(可选)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='转赠时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_gifts_received', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_gifts_sent', to=settings.AUTH_USER_MODEL, verbose_name='转赠人')),
            ],
            options={
                'verbose_name': '积分转赠',
                'verbose_name_plural': '积分转赠',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, verbose_name='兑换码')),
                ('amount', models.PositiveIntegerField(verbose_name='面额(积分)')),
                ('status', models.CharField(choices=[('active', '待核销'), ('used', '已核销'), ('revoked', '已作废')], default='active', max_length=16, verbose_name='状态')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_vouchers_redeemed', to=settings.AUTH_USER_MODEL, verbose_name='核销人')),
            ],
            options={
                'verbose_name': '积分兑换码',
                'verbose_name_plural': '积分兑换码',
                'ordering': ['-created_at'],
            },
        ),
    ]
