# Generated by Django 5.2.16 on 2026-08-20

from django.db import migrations

DEFAULT_RULE = {
    'code': 'registration_bonus',
    'name': '新用户注册奖励',
    'points': 20,
    'enabled': True,
    'daily_limit': 1,
    'total_limit': 1,
    'description': '新用户注册成功后一次性发放的奖励积分（每人仅一次）。',
}


def seed_rule(apps, schema_editor):
    PointRule = apps.get_model('navigation', 'PointRule')
    PointRule.objects.update_or_create(
        code=DEFAULT_RULE['code'],
        defaults={
            'name': DEFAULT_RULE['name'],
            'points': DEFAULT_RULE['points'],
            'enabled': DEFAULT_RULE['enabled'],
            'daily_limit': DEFAULT_RULE['daily_limit'],
            'total_limit': DEFAULT_RULE['total_limit'],
            'description': DEFAULT_RULE['description'],
        },
    )


def remove_rule(apps, schema_editor):
    PointRule = apps.get_model('navigation', 'PointRule')
    PointRule.objects.filter(code=DEFAULT_RULE['code']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0036_alter_pointtransaction_ref_type_pointsgift_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_rule, remove_rule),
    ]