# Generated by Django 5.2.16 on 2026-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0037_seed_registration_bonus_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsetting',
            name='head_scripts',
        ),
        migrations.AddField(
            model_name='appsetting',
            name='adsense_publisher_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='AdSense 发布商 ID (ca-pub-xxx)'),
        ),
    ]
