import {
  AlertCircle,
  AlertTriangle,
  Apple,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUp,
  BookOpen,
  Camera,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CirclePlus,
  CloudOff,
  Copy,
  Download,
  ExternalLink,
  Eye,
  FileText,
  FlaskConical,
  Gift,
  Globe,
  Heart,
  HelpCircle,
  Home,
  Info,
  KeyRound,
  Layers,
  Link,
  List,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Megaphone,
  MessageSquare,
  Pencil,
  Play,
  Plus,
  Receipt,
  Redo2,
  RefreshCw,
  Search,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tags,
  Trash2,
  Trophy,
  User,
  UserCircle,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";
import type { StyleInput } from "./primitives";
import { flattenStyles } from "./primitives";

const ICONS: Record<string, LucideIcon> = {
  "open-outline": ExternalLink,
  "star": Star,
  "star-outline": Star,
  "search": Search,
  "arrow-back": ArrowLeft,
  "chevron-back": ChevronLeft,
  "chevron-forward": ChevronRight,
  "close": X,
  "checkmark": Check,
  "add": Plus,
  "refresh": RefreshCw,
  "download-outline": Download,
  "copy-outline": Copy,
  "home": Home,
  "person": User,
  "person-circle-outline": UserCircle,
  "person-outline": User,
  "favorites": Star,
  "gift": Gift,
  "gift-outline": Gift,
  "globe-outline": Globe,
  "log-in-outline": LogIn,
  "log-out-outline": LogOut,
  "logo-apple": Apple,
  "logo-google-playstore": Play,
  "logo-android": Smartphone,
  "mail-outline": Mail,
  "phone-portrait-outline": Smartphone,
  "key-outline": KeyRound,
  "lock-closed-outline": Lock,
  "share-social-outline": Share2,
  "shield-checkmark-outline": ShieldCheck,
  "sparkles-outline": Sparkles,
  "trophy-outline": Trophy,
  "book-outline": BookOpen,
  "chatbubbles-outline": MessageSquare,
  "document-text-outline": FileText,
  "play-circle-outline": Play,
  "people-outline": Users,
  "camera-outline": Camera,
  "albums-outline": Layers,
  "flask-outline": FlaskConical,
  "pricetags-outline": Tags,
  "receipt-outline": Receipt,
  "storefront-outline": Store,
  "arrow-up": ArrowUp,
  "arrow-redo-outline": Redo2,
  "alert-circle": AlertCircle,
  "warning-outline": AlertTriangle,
  "help-circle-outline": HelpCircle,
  "information-circle-outline": Info,
  "swap-horizontal": ArrowLeftRight,
  "cloud-offline-outline": CloudOff,
  "megaphone": Megaphone,
  "add-circle-outline": CirclePlus,
  "checkmark-circle": CheckCircle2,
  "heart": Heart,
  "heart-outline": Heart,
  "eye-outline": Eye,
  "cart-outline": ShoppingCart,
  "list-outline": List,
  "link-outline": Link,
  "pencil-outline": Pencil,
  "trash-outline": Trash2,
};

interface IoniconsProps {
  name: string;
  size?: number;
  color?: string;
  style?: StyleInput;
}

export function Ionicons({ name, size = 20, color = "currentColor", style }: IoniconsProps) {
  const Icon = ICONS[name] ?? Info;
  return <Icon size={size} color={color} style={flattenStyles(style)} aria-hidden="true" />;
}

export function MapIcon(name: string): LucideIcon {
  return ICONS[name] ?? Info;
}

export default Ionicons;