"""演示数据：分类 + 国际主流金融/Web3 站点（约 300 个）。

用法:
    python manage.py seed_demo
命令可重复执行（幂等，按 slug / name + category get_or_create/update_or_create）。

命名约定：name 用英文原名，description 用中文说明。
站点按分类分组，sort_order 在命令内按分类顺序自动递增。
"""
from django.core.management.base import BaseCommand

from apps.navigation.models import Category, Site, Tag

CATEGORIES = [
    {'name': 'DeFi', 'slug': 'defi', 'icon': '🦄', 'sort_order': 1},
    {'name': '交易所', 'slug': 'exchange', 'icon': '🏦', 'sort_order': 2},
    {'name': '钱包', 'slug': 'wallet', 'icon': '👛', 'sort_order': 3},
    {'name': '行情资讯', 'slug': 'market', 'icon': '📈', 'sort_order': 4},
    {'name': '海外券商', 'slug': 'broker', 'icon': '📊', 'sort_order': 5},
    {'name': '海外银行', 'slug': 'bank', 'icon': '🏛️', 'sort_order': 6},
    {'name': 'U卡', 'slug': 'ucard', 'icon': '💳', 'sort_order': 7},
    {'name': '区块链浏览器', 'slug': 'explorer', 'icon': '🔭', 'sort_order': 8},
    {'name': '数据分析', 'slug': 'analytics', 'icon': '🧮', 'sort_order': 9},
    {'name': '支付收款', 'slug': 'payment', 'icon': '💰', 'sort_order': 10},
]


def _s(name, url, description, tags=()):
    """构造单条站点数据（name 英文原名，description 中文说明）。"""
    return {
        'name': name,
        'url': url,
        'description': description,
        'tags': list(tags),
    }


SITES_BY_CATEGORY = {
    'defi': [
        _s('Uniswap', 'https://uniswap.org', '全球最流行的去中心化交易所（DEX），自动做市商模式的先驱。',
           ('dex', 'swap', 'amm'),
        _s('Aave (AAVE)', 'https://aave.com', '领先的去中心化借贷协议，支持存入资产赚取利息或抵押借款。',
           ('lending', '借贷')),
        _s('Curve Finance', 'https://curve.fi', '专为稳定币设计的低滑点兑换协议，也是稳定币流动性主力。',
           ('dex', 'stablecoin', 'amm')),
        _s('Lido', 'https://lido.fi', '以太坊流动性质押协议，质押 ETH 可换取 stETH 并获得收益。',
           ('staking', '质押', 'eth')),
        _s('1inch', 'https://1inch.io', '聚合 DEX 流动性寻找最优兑换路径的聚合器，支持多链。',
           ('dex', 'aggregator', 'swap')),
        _s('Compound', 'https://compound.finance', '老牌链上借贷协议，支持多种主流资产抵押借款。',
           ('lending', '借贷', 'cToken')),
        _s('PancakeSwap', 'https://pancakeswap.finance', 'BNB Chain 上最流行的 DEX，内置收益农场与彩票。',
           ('dex', 'amm', 'bsc')),
        _s('GMX', 'https://gmx.io', 'GMX V2 多链永续合约 DEX，跨资产抵押与低滑点。',
           ('perps', 'dex', '合约')),
        _s('SushiSwap', 'https://www.sushi.com', '多链 DEX 与收益聚合平台，寿司核心奖励机制。',
           ('dex', 'amm', 'yield')),
        _s('Balancer', 'https://balancer.fi', '可自定义权重与多资产池的 AMM 协议，适合做组合指数池。',
           ('dex', 'amm', 'multi-asset')),
        _s('MakerDAO (Spark)', 'https://makerdao.com', '发行稳定币 DAI 的借贷协议，治理与储蓄生态成熟。',
           ('stablecoin', 'lending', 'dai')),
        _s('Ethena', 'https://www.ethena.fi', '基于对冲策略的合成美元稳定币 sUSDe 发行方。',
           ('stablecoin', 'yield', 'synthetic')),
        _s('Ondo Finance', 'https://ondo.finance', '将美国国债代币化，提供链上美债收益产品。',
           ('rwa', 'yield', 'treasury')),
        _s('Jupiter', 'https://jupiter.com', 'Solana 生态最大的 DEX 聚合器与永续合约平台。',
           ('dex', 'aggregator', 'solana')),
        _s('Raydium', 'https://raydium.io', 'Solana 上最流行的 AMM，与 Serum 订单簿深度集成。',
           ('dex', 'amm', 'solana')),
        _s('Orca', 'https://www.orca.so', 'Solana 上主打易用性的集中流动性 DEX。',
           ('dex', 'amm', 'solana')),
        _s('Meteora', 'https://meteora.ag', 'Solana 生态的动态 AMM 与流动性管理协议。',
           ('dex', 'amm', 'solana')),
        _s('Drift', 'https://www.drift.trade', 'Solana 上的去中心化永续合约交易所。',
           ('perps', 'dex', 'solana')),
        _s('Hyperliquid', 'https://hyperliquid.xyz', '高性能链上永续合约交易平台，订单簿自建链上。',
           ('perps', 'dex', '订单簿')),
        _s('dYdX', 'https://dydx.exchange', '基于订单簿的去中心化永续合约交易所。',
           ('perps', 'dex')),
        _s('Synthetix', 'https://synthetix.io', '合成资产协议，可交易黄金、股票等链上合成资产。',
           ('synthetic', 'derivatives')),
        _s('Yearn Finance', 'https://yearn.finance', '收益聚合平台，自动寻找 DeFi 最优收益策略。',
           ('yield', 'vault')),
        _s('Convex Finance', 'https://www.convexfinance.com', 'Curve 流动性提供者的收益放大器。',
           ('yield', 'curve', 'vault')),
        _s('Beefy', 'https://beefy.com', '跨链收益聚合器，自动复投多链收益农场。',
           ('yield', 'auto-compound')),
        _s('Aerodrome', 'https://aerodrome.finance', 'Base 链核心流动性市场与 AMM，veTokenomics 激励。',
           ('dex', 'amm', 'base')),
        _s('Morpho', 'https://morpho.org', '优化借贷撮合的 DeFi 协议，借出方/借款方都更优。',
           ('lending', '借贷')),
        _s('Gearbox', 'https://gearbox.fi', '可组合杠杆协议，允许借贷后进行复杂策略操作。',
           ('leverage', 'lending')),
        _s('Liquity', 'https://www.liquity.org', '免清算线的高资本效率稳定币协议 LUSD。',
           ('stablecoin', 'lending')),
        _s('Frax Finance', 'https://frax.finance', '部分抵押的稳定币协议与收益生态。',
           ('stablecoin', 'yield')),
        _s('Abracadabra', 'https://abracadabra.money', '发行魔法稳定币 MIM 的借贷与收益协议。',
           ('stablecoin', 'lending')),
        _s('GMX V2', 'https://gmx.io', 'GMX V2 多链永续合约，跨资产抵押与更低滑点。',
           ('perps', 'dex', '合约')),
        _s('Stargate', 'https://stargate.finance', '基于 LayerZero 的跨链稳定币桥，流动性共享。',
           ('bridge', 'cross-chain')),
        _s('Across', 'https://across.to', '快速跨链桥，支持多条 EVM 链与稳定币即速到账。',
           ('bridge', 'cross-chain')),
        _s('Hop Protocol', 'https://hop.exchange', '基于 Rollup 桥的跨链资产转账协议。',
           ('bridge', 'cross-chain')),
        _s('Jito', 'https://www.jito.wtf', 'Solana 流动性质押与 MEV 生态项目，质押 jSOL。',
           ('staking', 'solana')),
        _s('Marinade', 'https://marinade.finance', 'Solana 最大流动性质押协议，质押 mSOL。',
           ('staking', 'solana')),
        _s('Blast', 'https://blast.io', '以太坊 L2，原生收益机制吸引大量 DeFi 应用。',
           ('l2', 'yield')),
    ],
    'exchange': [
        _s('Binance 币安', 'https://www.binance.com', '全球交易量最大的加密货币交易所，支持现货、合约、理财等全业务。',
           ('cex', '现货', '合约')),
        _s('OKX 欧易', 'https://www.okx.com', '全球化数字资产交易平台，提供现货、合约、期权与 Web3 钱包。',
           ('cex', '交易')),
        _s('Coinbase', 'https://www.coinbase.com', '美国合规的加密货币交易所，适合新手，支持美元入金。',
           ('cex', '合规')),
        _s('Kraken', 'https://www.kraken.com', '老牌欧美合规交易所，支持现货、合约与 Staking。',
           ('cex', '合规', '美欧')),
        _s('Bybit 必安', 'https://www.bybit.com', '衍生品交易量领先的交易所，现货与合约深度俱佳。',
           ('cex', '合约', 'derivatives')),
        _s('KuCoin 库币', 'https://www.kucoin.com', '提供海量小币种上架与多种交易方式的全球化平台。',
           ('cex', '小币种')),
        _s('Bitget', 'https://www.bitget.com', '聚焦合约与跟单交易的国际化交易所。',
           ('cex', '合约', '跟单')),
        _s('Crypto.com', 'https://crypto.com', '全球化加密交易所与 App，配套加密 Visa 卡与理财。',
           ('cex', 'app')),
        _s('Gate.io', 'https://www.gate.io', '老牌中文友好交易所，提供现货、合约与理财。',
           ('cex', '中文')),
        _s('MEXC', 'https://www.mexc.com', '以极多上架币种和低手续费著称的交易所。',
           ('cex', '小币种')),
        _s('BingX', 'https://bingx.com', '社交跟单与合约见长的国际化交易所。',
           ('cex', '合约', '跟单')),
        _s('Bitfinex', 'https://www.bitfinex.com', '深耕机构与做市的老牌交易所，支持法币充提。',
           ('cex', '机构')),
        _s('Kraken Pro', 'https://pro.kraken.com', 'Kraken 的专业交易界面，低费率与高级订单类型。',
           ('cex', '专业')),
        _s('Poloniex', 'https://poloniex.com', '老牌交易所，交易对与代币种类丰富。',
           ('cex', '老牌')),
        _s('HTX (火币)', 'https://www.htx.com', '原火币全球站，面向海外用户的主流交易所。',
           ('cex', '中文')),
        _s('Bitget Wallet', 'https://www.bitget.com', 'Bitget 生态多链钱包与聚合交易入口。',
           ('cex', 'wallet')),
        _s('Deribit', 'https://www.deribit.com', '全球期权交易量最大的加密衍生品交易所。',
           ('options', '衍生品')),
        _s('Kraken Futures', 'https://futures.kraken.com', 'Kraken 旗下永续合约平台。',
           ('cex', '合约')),
        _s('OKX DEX', 'https://www.okx.com/web3', 'OKX Web3 聚合器与多链钱包入口。',
           ('dex', 'web3')),
        _s('Binance US', 'https://www.binance.us', '币安美国站，服务美国合规用户。',
           ('cex', '美国')),
        _s('Gemini', 'https://www.gemini.com', 'Winklevoss 兄弟创办的美国合规交易所。',
           ('cex', '合规')),
        _s('Bitstamp', 'https://www.bitstamp.net', '欧洲老牌合规交易所，支持法币入金。',
           ('cex', '欧洲')),
        _s('LMAX Digital', 'https://www.lmaxdigital.com', '面向机构的加密现货交易场所。',
           ('institutional', '机构')),
        _s('Phemex', 'https://phemex.com', '合约见长的国际化交易所，界面简洁。',
           ('cex', '合约')),
        _s('OKX Wallet', 'https://www.okx.com/web3', 'OKX 官方多链钱包与 DApp 浏览器。',
           ('wallet', 'web3')),
        _s('KuCoin Futures', 'https://www.kucoin.com/futures', '库币合约交易平台，合约品种丰富。',
           ('cex', '合约')),
        _s('Bitrue', 'https://www.bitrue.com', '支持借贷与打新的中小型交易所。',
           ('cex', 'lending')),
        _s('Huobi Global', 'https://www.huobi.com', '曾经的头部交易所，现面向全球运营。',
           ('cex', '老牌')),
        _s('Latoken', 'https://latoken.com', '提供代币首发（IDO）与创新的交易平台。',
           ('cex', 'ido')),
        _s('Backpack', 'https://backpack.exchange', 'Solana 系新锐合规交易所，界面现代。',
           ('cex', 'solana')),
        _s('WhiteBIT', 'https://whitebit.com', '欧洲地区增长迅速的合规交易所。',
           ('cex', '欧洲')),
        _s('ApeX', 'https://apex.exchange', '基于订单簿的 DEX 合约交易平台。',
           ('perps', 'dex')),
        _s('Vertex', 'https://vertexprotocol.com', '多链永续合约 DEX，主打低费率。',
           ('perps', 'dex')),
        _s('dYdX Chain', 'https://dydx.trade', '基于 Cosmos 的 dYdX 全新订单簿链。',
           ('perps', 'dex')),
    ],
    'wallet': [
        _s('MetaMask 小狐狸', 'https://metamask.io', '最流行的以太坊浏览器插件钱包，也是 DeFi 生态的入口。',
           ('wallet', 'ethereum', '浏览器插件')),
        _s('Trust Wallet 信任钱包', 'https://trustwallet.com', '币安官方推出的多链移动钱包，支持数千种代币。',
           ('wallet', 'mobile')),
        _s('Phantom 幻影', 'https://phantom.app', 'Solana 生态最受欢迎的浏览器钱包与移动钱包。',
           ('wallet', 'solana')),
        _s('Ledger', 'https://www.ledger.com', '全球最知名的硬件钱包，冷存储安全首选。',
           ('hardware-wallet', '冷钱包')),
        _s('Trezor', 'https://trezor.io', '开源的硬件钱包，强调透明与可审计性。',
           ('hardware-wallet', '冷钱包')),
        _s('Exodus', 'https://www.exodus.com', '界面精美的桌面/移动多币种钱包，内置兑换功能。',
           ('wallet', 'multi-coin')),
        _s('Rabby', 'https://rabby.io', '以太坊生态的多账户浏览器钱包，支持多链自动切换。',
           ('wallet', 'ethereum', '浏览器插件')),
        _s('Argent', 'https://www.argent.xyz', '智能合约钱包，社交恢复、无助记词门槛。',
           ('smart-wallet', 'social-recovery')),
        _s('SafePal', 'https://www.safepal.com', '硬件+软件双形态的多链钱包，支持二维码离线签名。',
           ('hardware-wallet', 'wallet')),
        _s('Keystone', 'https://keyst.one', '开源硬件钱包，QR 通信离线签名安全。',
           ('hardware-wallet', '冷钱包')),
        _s('OneKey', 'https://onekey.so', '硬件钱包与软件钱包一体化的国产 Web3 钱包。',
           ('hardware-wallet', 'wallet')),
        _s('TokenPocket', 'https://www.tokenpocket.io', '多链移动钱包，支持 DApp 浏览与质押。',
           ('wallet', 'mobile')),
        _s('BitKeep (Bitget Wallet)', 'https://web3.bitget.com', '多链钱包，Web3 生态应用丰富。',
           ('wallet', 'mobile')),
        _s('imToken', 'https://token.im', '国内知名以太坊钱包，支持多链与 DApp。',
           ('wallet', '中文')),
        _s('Rainbow', 'https://rainbow.me', '以太坊生态的移动钱包，UI 精致、NFT 友好。',
           ('wallet', 'nft', 'ethereum')),
        _s('Zerion', 'https://zerion.io', '跨链投资管理钱包，聚合交易与 DeFi 资产展示。',
           ('wallet', 'portfolio')),
        _s('Coinbase Wallet', 'https://www.coinbase.com/wallet', 'Coinbase 官方自托管钱包，与交易所互通。',
           ('wallet', 'self-custody')),
        _s('Electrum', 'https://electrum.org', '比特币老牌轻客户端钱包，功能强大且开源。',
           ('wallet', 'bitcoin')),
        _s('Sparrow Wallet', 'https://sparrowwallet.com', '功能强大的比特币桌面钱包，注重隐私与 PSBT。',
           ('wallet', 'bitcoin')),
        _s('BlueWallet', 'https://bluewallet.com', '比特币移动钱包，支持闪电网络。',
           ('wallet', 'bitcoin', 'lightning')),
        _s('Klever', 'https://klever.io', '多链移动钱包与 DeFi 入口。',
           ('wallet', 'mobile')),
        _s('Math Wallet', 'https://mathwallet.org', '支持数十条链的多链浏览器钱包。',
           ('wallet', 'multi-chain')),
        _s('WalletConnect', 'https://walletconnect.com', '钱包与 DApp 连接的标准协议与基础设施。',
           ('protocol', 'web3')),
        _s('Safe (Gnosis Safe)', 'https://safe.global', '多签钱包行业标准，DAO 与团队资产管理首选。',
           ('multisig', 'safe')),
        _s('Ambire', 'https://www.ambire.com', '智能合约钱包，免助记词、Gas 代付。',
           ('smart-wallet',)),
        _s('ZenGo', 'https://zengo.com', '基于 MPC 技术的无助记词手机钱包。',
           ('smart-wallet', 'mpc')),
        _s('Coin98', 'https://coin98.com', '多链钱包与 DeFi 入口，覆盖主流链。',
           ('wallet', 'multi-chain')),
        _s('BitPay', 'https://bitpay.com', '比特币/加密支付钱包，支持账单与商户收款。',
           ('wallet', 'payment')),
        _s('Xverse', 'https://www.xverse.app', '比特币生态钱包，支持 Ordinals 与 Stacks。',
           ('wallet', 'bitcoin')),
        _s('Uniswap Wallet', 'https://uniswap.org/wallet', 'Uniswap 官方移动钱包，多链原生。',
           ('wallet', 'mobile')),
    ],
    'market': [
        _s('CoinMarketCap (CMC)', 'https://coinmarketcap.com', '全球最权威的加密货币行情与市值排名网站。',
           ('行情', '市值', 'ranking')),
        _s('CoinGecko', 'https://www.coingecko.com', '全球加密货币数据聚合平台，覆盖大量币种与交易对。',
           ('行情', '数据')),
        _s('律动 BlockBeats', 'https://www.theblockbeats.info', '中文区块链媒体，提供快讯、深度报道与行业洞察。',
           ('资讯', '新闻')),
        _s('TradingView', 'https://www.tradingview.com', '全球最受欢迎的金融图表平台，支持加密/股票/外汇。',
           ('图表', '行情')),
        _s('CoinCodex', 'https://coincodex.com', '加密货币价格追踪与预测工具站。',
           ('行情', '预测')),
        _s('CoinMarketCal', 'https://coinmarketcal.com', '加密货币事件日历，跟踪上线、解锁等时间节点。',
           ('事件日历', '资讯')),
        _s('The Block', 'https://www.theblock.co', '美国权威区块链媒体与研究机构。',
           ('资讯', '研究')),
        _s('CoinDesk', 'https://www.coindesk.com', '全球知名加密新闻媒体，行业风向标之一。',
           ('资讯', '新闻')),
        _s('Decrypt', 'https://decrypt.co', '面向大众的加密新闻与科普媒体。',
           ('资讯', '科普')),
        _s('PANews 潘可', 'https://www.panewslab.com', '中文区块链资讯与行情聚合平台。',
           ('资讯', '中文')),
        _s('Odaily 星球日报', 'https://www.odaily.news', '中文区块链媒体，覆盖一级市场与行业动态。',
           ('资讯', '中文')),
        _s('链捕手 ChainCatcher', 'https://www.chaincatcher.com', '区块链深度研究与快讯的中文平台。',
           ('资讯', '中文')),
        _s('Bitcoin Magazine', 'https://bitcoinmagazine.com', '比特币领域历史最悠久的媒体。',
           ('资讯', '比特币')),
        _s('Cointelegraph', 'https://cointelegraph.com', '覆盖广泛的加密新闻媒体，多语言报道。',
           ('资讯', '新闻')),
        _s('CryptoSlate', 'https://cryptoslate.com', '加密新闻与代币数据聚合站。',
           ('资讯', '数据')),
        _s('CoinFabrik', 'https://www.coinfabrik.com', '区块链安全审计与研发机构。',
           ('审计', '安全')),
        _s('PeckShield', 'https://peckshield.com', '头部区块链安全公司，专注智能合约审计与监控。',
           ('审计', '安全')),
        _s('CertiK', 'https://www.certik.com', 'Web3 安全审计与监控平台，提供评分。',
           ('审计', '安全')),
        _s('CoinGecko API', 'https://www.coingecko.com/en/api', 'CoinGecko 公开行情 API，开发者常用。',
           ('api', '数据')),
        _s('Messari', 'https://messari.io', '加密行业研究平台，提供研报与数据看板。',
           ('研究', '数据')),
        _s('Nansen', 'https://www.nansen.ai', '链上数据智能平台，追踪聪明钱与地址画像。',
           ('链上数据', '研究')),
        _s('Dune', 'https://dune.com', '链上数据查询与仪表盘平台，社区共享分析。',
           ('链上数据', 'sql')),
        _s('Glassnode', 'https://glassnode.com', '链上数据分析平台，提供深度链上指标。',
           ('链上数据', '分析')),
        _s('CryptoQuant', 'https://cryptoquant.com', '交易所数据与链上资金流分析平台。',
           ('链上数据', '分析')),
    ],
    'broker': [
        _s('Interactive Brokers 盈透证券', 'https://www.interactivebrokers.com', '全球最顶级的券商之一，支持美股、港股、期权、期货，佣金低，适合跨境投资。',
           ('美股', '港股', '期权', '期货')),
        _s('Charles Schwab 嘉信理财', 'https://www.schwab.com', '美国最大的零售券商之一，股票与 ETF 零佣金，支持 ACH 转账与全球日交易。',
           ('美股', 'ETF', '零佣金')),
        _s('Firstrade 第一证券', 'https://www.firstrade.com', '美股与期权全免佣金，提供中文界面，深受海外华人投资者喜爱。',
           ('美股', '期权', '零佣金', '中文')),
        _s('moomoo 富途', 'https://www.moomoo.com', '富途旗下全球证券平台，覆盖美股、港股、A股，免费行情与社区资讯。',
           ('美股', '港股', '中文')),
        _s('Tiger Brokers 老虎证券', 'https://www.tigerbrokers.com', '国际化券商，覆盖美股、港股、A股及期权期货，一键投资全球市场。',
           ('美股', '港股', '中文')),
        _s('Webull 微牛', 'https://www.webull.com', '美股零佣金券商，图表工具强大，支持盘前盘后交易与纸面模拟。',
           ('美股', '零佣金')),
        _s('Fidelity', 'https://www.fidelity.com', '美国最大资管与零售券商之一，股票 ETF 零佣金，研究工具丰富。',
           ('美股', 'ETF', '零佣金')),
        _s('Vanguard', 'https://investor.vanguard.com', '指数基金与 ETF 巨头，长期投资与养老账户首选。',
           ('ETF', '指数基金')),
        _s('Robinhood', 'https://robinhood.com', '零佣金散户券商，移动端体验优秀，支持期权与加密。',
           ('美股', '零佣金', '移动')),
        _s('E*TRADE', 'https://us.etrade.com', '老牌零佣金美股券商，工具全面。',
           ('美股', '零佣金')),
        _s('TD Ameritrade', 'https://www.tdameritrade.com', '知名美股券商，现并入嘉信理财生态。',
           ('美股', '期权')),
        _s('SogoTrade', 'https://www.sogotrade.com', '面向华人用户的美股券商，费率透明。',
           ('美股', '中文')),
        _s('Interactive Brokers 香港', 'https://www.ibkr.com', '盈透证券香港站，支持港股与离岸服务。',
           ('港股', '全球')),
        _s('Saxo Bank', 'https://www.home.saxo', '丹麦投行级多资产交易平台，覆盖全球市场。',
           ('多资产', '全球')),
        _s('Lightspeed', 'https://www.lightspeed.com', '活跃美股日交易者喜爱的券商，执行速度快。',
           ('美股', '日交易')),
        _s('TradeStation', 'https://www.tradestation.com', '专业交易平台，支持股票、期货与外汇。',
           ('美股', '期货')),
        _s('DEGIRO', 'https://www.degiro.com', '欧洲流行的低费率零售券商。',
           ('欧洲', '低费率')),
        _s('Freedom Finance', 'https://www.freedom24.com', '美国与欧洲市场的全球性券商。',
           ('全球', '多市场')),
        _s('Longbridge 长桥', 'https://www.longbridge.com', '面向港美股用户的新兴互联网券商。',
           ('港股', '美股', '中文')),
        _s('Zerodha', 'https://zerodha.com', '印度最大零售券商，经纪费极低。',
           ('印度', '低费率')),
        _s('Hargreaves Lansdown', 'https://www.hl.co.uk', '英国最大零售投资平台之一。',
           ('英国', 'ISA')),
        _s('Revolut Trading', 'https://www.revolut.com', 'Revolut 内置股票交易，支持美股分股。',
           ('美股', '移动')),
        _s('BUX', 'https://www.bux.com', '欧洲移动优先的零售交易平台。',
           ('欧洲', '移动')),
        _s('Pepperstone', 'https://pepperstone.com', '澳大利亚知名外汇与差价合约券商。',
           ('外汇', 'CFD')),
        _s('IC Markets', 'https://www.icmarkets.com', '澳大利亚零售外汇龙头，点差低。',
           ('外汇', 'CFD')),
        _s('OANDA', 'https://www.oanda.com', '全球知名外汇交易平台，透明报价。',
           ('外汇', 'CFD')),
        _s('FOREX.com', 'https://www.forex.com', '大型外汇与差价合约经纪商。',
           ('外汇', 'CFD')),
        _s('Schwab International', 'https://www.schwab.com/intl', '嘉信国际账户，方便非美国居民开户。',
           ('国际', '美股')),
        _s('Merill Edge', 'https://www.merrilledge.com', '美银旗下零售券商，与银行账户联动。',
           ('美股', '银行')),
        _s('Sofi Invest', 'https://www.sofi.com/invest', 'Sofi 生态的零佣金投资平台。',
           ('美股', '零佣金')),
        _s('Wealthfront', 'https://www.wealthfront.com', '智能投顾平台，自动化资产管理。',
           ('robo-advisor', '智能投顾')),
    ],
    'bank': [
        _s('HSBC 汇丰银行', 'https://www.hsbc.com', '全球性银行，多币种账户与全球转账便捷，适合跨国资金管理。',
           ('多币种', '全球')),
        _s('Standard Chartered 渣打银行', 'https://www.sc.com', '业务覆盖亚洲、非洲与中东，提供多币种账户与跨境金融服务。',
           ('多币种', '跨境')),
        _s('DBS 星展银行', 'https://www.dbs.com', '新加坡最大银行，多币种账户与成熟的数字银行服务。',
           ('多币种', '新加坡')),
        _s('Citibank 花旗银行', 'https://www.citibank.com', '国际零售银行集团，支持全球多币种账户与跨境交易。',
           ('多币种', '全球')),
        _s('Wise 跨境汇款', 'https://wise.com', '国际转账与多币种账户，按实时中间汇率且手续费透明。',
           ('多币种', '转账')),
        _s('Revolut', 'https://www.revolut.com', '数字银行与多币种账户，实时汇率兑换，支持虚拟借记卡。',
           ('多币种', '数字银行')),
        _s('N26', 'https://n26.com', '德国数字银行，多币种账户与优秀移动体验。',
           ('数字银行', '欧洲')),
        _s('Monzo', 'https://monzo.com', '英国热门数字银行，主打预算管理与即时支付。',
           ('数字银行', '英国')),
        _s('Chase 摩根大通', 'https://www.chase.com', '美国最大银行之一，账户体系与信用卡丰富。',
           ('美国', '信用卡')),
        _s('Barclays 巴克莱', 'https://www.barclays.co.uk', '英国老牌大型银行，个人与企业金融服务齐全。',
           ('英国', '传统银行')),
        _s('BNP Paribas 法国巴黎银行', 'https://group.bnpparibas.com', '法国最大银行集团，欧洲金融服务巨头。',
           ('欧洲', '传统银行')),
        _s('OCBC 华侨银行', 'https://www.ocbc.com', '新加坡本土银行，东南亚网络密集。',
           ('新加坡', '东南亚')),
        _s('UOB 大华银行', 'https://www.uob.com.sg', '新加坡主要银行，亚太业务广泛。',
           ('新加坡', '亚太')),
        _s('Maybank 马来亚银行', 'https://www.maybank.com', '东南亚最大银行之一，覆盖多国零售业务。',
           ('东南亚', '传统银行')),
        _s('Wise Business', 'https://wise.com/business', 'Wise 企业账户，多币种收款与低费用转账。',
           ('企业', '转账')),
        _s('Bank of America', 'https://www.bankofamerica.com', '美国第二大银行，零售与信用卡业务庞大。',
           ('美国', '传统银行')),
        _s('Wells Fargo', 'https://www.wellsfargo.com', '美国大型银行，个人金融服务全面。',
           ('美国', '传统银行')),
        _s('Citizens Bank', 'https://www.citizensbank.com', '美国东北部区域银行，零售账户服务齐全。',
           ('美国', '区域银行')),
        _s('WISE (原 TransferWise)', 'https://wise.com', '国际转账定价透明的经典平台，实时汇率。',
           ('转账', '多币种')),
        _s('Payoneer', 'https://www.payoneer.com', '面向自由职业者与跨境电商的全球收款账户。',
           ('收款', '跨境')),
        _s('Airwallex', 'https://www.airwallex.com', '企业级跨境支付与多币种账户平台。',
           ('企业', '跨境')),
        _s('Mercury', 'https://mercury.com', '面向初创公司的美国数字银行，企业账户友好。',
           ('企业', '美国')),
        _s('Brex', 'https://www.brex.com', '为创业公司设计的商业账户与公司卡。',
           ('企业', '美国')),
        _s('Starling Bank', 'https://www.starlingbank.com', '英国数字银行，主打中小企业与个人。',
           ('数字银行', '英国')),
        _s('Atom Bank', 'https://www.atombank.co.uk', '英国纯数字银行，储蓄利率有竞争力。',
           ('数字银行', '英国')),
        _s('Klarna', 'https://www.klarna.com', '欧洲先买后付（BNPL）与储蓄功能。',
           ('BNPL', '欧洲')),
        _s('WISE卡', 'https://wise.com', 'Wise 多币种借记卡，全球消费免手续费。',
           ('借记卡', '多币种')),
        _s('Crypto Bank', 'https://www.xapo.com', '加密友好银行，支持比特币存款与 Visa 卡。',
           ('加密银行', 'Visa')),
        _s('Fidor Bank', 'https://www.fidor.com', '德国社区化数字银行，早年创新代表。',
           ('数字银行', '欧洲')),
        _s('Green Dot Bank', 'https://www.greendot.com', '美国预付卡与数字银行服务商。',
           ('美国', '预付')),
        _s('Ally Bank', 'https://www.ally.com', '美国高收益储蓄数字银行，无月费。',
           ('储蓄', '美国')),
        _s('Capital One', 'https://www.capitalone.com', '美国大型数字优先银行与信用卡发卡行。',
           ('美国', '信用卡')),
    ],
    'ucard': [
        _s('Wirex', 'https://wirexapp.com', '加密 Visa 借记卡，支持 BTC、USDT 等稳定币直接消费并获得返现。',
           ('加密卡', 'Visa', 'USDT')),
        _s('Crypto.com Card', 'https://crypto.com', 'Crypto.com 推出的加密 Visa 卡，质押 CRO 可提升消费返现比例。',
           ('加密卡', 'Visa', '返现')),
        _s('RedotPay 红点支付', 'https://www.redotpay.com', 'USDT/加密充值 Visa 预付卡，支持 Apple Pay 与全球消费支付。',
           ('USDT卡', 'Visa', '预付卡')),
        _s('Depay 滴付', 'https://www.depay.com', 'USDT 充值 Visa/Mastercard 预付卡，覆盖订阅、电商等海外消费场景。',
           ('USDT卡', 'Visa', 'Mastercard')),
        _s('OneKey Card', 'https://card.onekey.so', '硬件钱包团队推出的加密 Visa 卡，支持 BTC、ETH、USDT 充值消费。',
           ('加密卡', 'Visa')),
        _s('Xapo Bank', 'https://www.xapo.com', '加密友好银行，支持比特币与美元存款并附 Visa 借记卡，存款有利息。',
           ('加密银行', 'Visa', '比特币')),
        _s('Bybit Card', 'https://www.bybit.com', 'Bybit 交易所推出的加密 Visa 卡，支持 USDT 支付返现。',
           ('加密卡', 'Visa')),
        _s('Binance Card', 'https://www.binance.com', '币安加密借记卡，消费按 BNB 返现（部分地区停发）。',
           ('加密卡', 'Visa')),
        _s('Ledger Pay', 'https://www.ledger.com', 'Ledger 生态支付与加密卡服务。',
           ('加密卡', '支付')),
        _s('Visa Crypto Card (Wirex)', 'https://wirexapp.com', 'Wirex 实体/虚拟加密卡双形态。',
           ('加密卡', 'Visa')),
        _s('Anvepay', 'https://anvepay.com', 'USDT 充值预付卡与虚拟卡服务。',
           ('USDT卡', '预付卡')),
        _s('Uquid', 'https://uquid.com', '基于加密的预付卡与数字礼品卡市场。',
           ('加密卡', '预付卡')),
        _s('Nexo Card', 'https://nexo.com', 'Nexo 借贷平台推出的加密卡，消费返现。',
           ('加密卡', 'Visa')),
        _s('Cake DeFi Card', 'https://cakedefi.com', 'Cake DeFi 生态加密卡与赚息服务。',
           ('加密卡', 'DeFi')),
        _s('Curve (by Wirex)', 'https://wirexapp.com', 'Wirex 与 Curve 联名卡整合支付。',
           ('加密卡', '聚合')),
        _s('CoinJar Card', 'https://www.coinjar.com', '澳洲加密卡与交易平台。',
           ('加密卡', '澳洲')),
        _s('Bybit Virtual Card', 'https://www.bybit.com', 'Bybit 虚拟 Visa 卡，无实体，线上消费。',
           ('加密卡', '虚拟卡')),
        _s('OKX Card', 'https://www.okx.com', 'OKX 生态加密支付卡（部分地区）。',
           ('加密卡', 'Visa')),
        _s('Kraken Card', 'https://www.kraken.com', 'Kraken 欧洲推出的加密借记卡。',
           ('加密卡', '欧洲')),
        _s('Juno', 'https://juno.finance', '美国加密银行账户，支持稳定币存款与借记卡返现。',
           ('加密卡', '美国')),
    ],
    'explorer': [
        _s('Etherscan', 'https://etherscan.io', '以太坊最权威的区块浏览器，查询地址、交易与合约。',
           ('以太坊', '浏览器')),
        _s('Solscan', 'https://solscan.io', 'Solana 生态主流区块浏览器。',
           ('solana', '浏览器')),
        _s('BscScan', 'https://bscscan.com', 'BNB Chain 官方区块浏览器。',
           ('bsc', '浏览器')),
        _s('PolygonScan', 'https://polygonscan.com', 'Polygon 网络的区块浏览器。',
           ('polygon', '浏览器')),
        _s('mempool.space', 'https://mempool.space', '比特币链上与矿工费实时监控开源浏览器。',
           ('bitcoin', '浏览器')),
        _s('OKLink', 'https://www.oklink.com', '多链区块浏览器与链上数据平台。',
           ('多链', '浏览器')),
        _s('Blockchair', 'https://blockchair.com', '多链隐私友好区块浏览器，支持数据导出。',
           ('多链', '浏览器')),
        _s('Arbiscan', 'https://arbiscan.io', 'Arbitrum L2 的区块浏览器。',
           ('arbitrum', '浏览器')),
        _s('Optimistic Etherscan', 'https://optimistic.etherscan.io', 'OP Mainnet 区块浏览器。',
           ('optimism', '浏览器')),
        _s('Basescan', 'https://basescan.org', 'Base L2 网络的区块浏览器。',
           ('base', '浏览器')),
        _s('ZkSync Era Explorer', 'https://explorer.zksync.io', 'zkSync Era L2 区块浏览器。',
           ('zksync', '浏览器')),
        _s('StarkNet Explorer', 'https://voyager.online', 'StarkNet 生态区块浏览器。',
           ('starknet', '浏览器')),
        _s('Solana Explorer', 'https://explorer.solana.com', 'Solana 官方区块浏览器。',
           ('solana', '浏览器')),
        _s('Avalanche Explorer', 'https://subnets.avax.network', 'Avalanche 多子网区块浏览器。',
           ('avalanche', '浏览器')),
        _s('PolygonPosScan', 'https://polygonscan.com', 'Polygon PoS 链浏览器（官方）。',
           ('polygon', '浏览器')),
        _s('TRONSCAN', 'https://tronscan.org', '波场 TRON 生态区块浏览器。',
           ('tron', '浏览器')),
        _s('Cardano Explorer', 'https://explorer.cardano.org', 'Cardano 官方区块浏览器。',
           ('cardano', '浏览器')),
        _s('Bitcoin Explorer', 'https://blockstream.info', 'Blockstream 比特币区块浏览器。',
           ('bitcoin', '浏览器')),
        _s('Chainalysis Explorer', 'https://www.chainalysis.com', '链上合规与调查平台（企业）。',
           ('合规', '链上')),
        _s('Nansen Explorer', 'https://www.nansen.ai', '链上地址画像与聪明钱追踪浏览器。',
           ('链上', '分析')),
        _s('DefiLlama Chain', 'https://defillama.com/chains', '各链 TVL 与生态数据汇总。',
           ('tvl', '多链')),
        _s('L2BEAT', 'https://l2beat.com', '以太坊 L2 扩容方案的数据与分析站点。',
           ('l2', '分析')),
        _s('Ultrasound.money', 'https://ultrasound.money', '以太坊燃烧与发行量实时监控。',
           ('eth', '监控')),
        _s('Token Terminal', 'https://tokenterminal.com', '公链与协议财务指标分析平台。',
           ('数据', '协议')),
        _s('Cryptofees', 'https://cryptofees.info', '各协议累计手续费实时排行。',
           ('数据', '手续费')),
    ],
    'analytics': [
        _s('DefiLlama', 'https://defillama.com', 'DeFi 数据聚合龙头，TVL 与协议排行权威。',
           ('tvl', '数据')),
        _s('Dune', 'https://dune.com', '链上数据 SQL 查询与仪表盘平台，社区共建分析。',
           ('链上数据', 'sql')),
        _s('Nansen', 'https://www.nansen.ai', '链上数据智能与地址画像平台，追踪聪明钱。',
           ('链上数据', '研究')),
        _s('Messari', 'https://messari.io', '加密行业研究平台，提供研报与数据看板。',
           ('研究', '数据')),
        _s('Token Terminal', 'https://tokenterminal.com', '公链与协议财务指标（收入/PE）分析平台。',
           ('数据', '协议')),
        _s('Glassnode', 'https://glassnode.com', '专业链上数据平台，提供深度链上指标。',
           ('链上数据', '分析')),
        _s('CryptoQuant', 'https://cryptoquant.com', '交易所资金流与链上数据分析平台。',
           ('链上数据', '分析')),
        _s('CoinGecko Data', 'https://www.coingecko.com', '加密货币市值与价格数据聚合。',
           ('数据', '行情')),
        _s('Santiment', 'https://santiment.net', '链上与社交情绪分析平台。',
           ('情绪', '数据')),
        _s('IntoTheBlock', 'https://www.intotheblock.com', '链上智能分析，地址层级持仓洞察。',
           ('链上数据', '分析')),
        _s('Arkham', 'https://arkhamintelligence.com', '链上地址实体标签与情报平台。',
           ('链上数据', '情报')),
        _s('Dune Analytics (Dune)', 'https://dune.com', '社区驱动的链上数据仪表盘。',
           ('链上数据', 'sql')),
        _s('Chainalysis', 'https://www.chainalysis.com', '区块链合规与调查数据分析平台。',
           ('合规', '数据')),
        _s('Elliptic', 'https://www.elliptic.co', '链上风险评估与合规数据服务。',
           ('合规', '风险')),
        _s('TRM Labs', 'https://www.trmlabs.com', '加密合规与风险监测平台。',
           ('合规', '风险')),
        _s('FalconX', 'https://www.falconx.io', '机构级加密交易与数据分析服务。',
           ('机构', '数据')),
        _s('Kaiko', 'https://www.kaiko.com', '机构级市场数据（价格/订单簿）提供商。',
           ('数据', '机构')),
        _s('Coin Metrics', 'https://coinmetrics.io', '专业的加密市场与链上数据指标。',
           ('数据', '指标')),
        _s('Delphi Digital', 'https://www.delphidigital.io', '加密研究机构，提供研报与数据。',
           ('研究', '数据')),
        _s('The Tie', 'https://www.thetie.io', 'AI 驱动的加密情报与数据平台。',
           ('数据', 'ai')),
        _s('Coinalyze', 'https://coinalyze.net', '期货市场数据分析与情绪指标。',
           ('衍生品', '数据')),
        _s('LunarCrush', 'https://lunarcrush.com', '社交情绪与影响力分析平台。',
           ('社交', '情绪')),
    ],
    'payment': [
        _s('PayPal', 'https://www.paypal.com', '全球最普及的在线支付平台，支持收款与转账。',
           ('支付', '收款')),
        _s('Stripe', 'https://stripe.com', '开发者友好的在线支付与商户基础设施。',
           ('支付', '商户')),
        _s('Payoneer', 'https://www.payoneer.com', '自由职业者与跨境电商收款账户，全球提现。',
           ('收款', '跨境')),
        _s('Airwallex', 'https://www.airwallex.com', '企业级跨境支付与多币种账户。',
           ('企业', '跨境')),
        _s('Circle', 'https://www.circle.com', '发行 USDC 稳定币的支付基础设施公司。',
           ('stablecoin', '支付')),
        _s('Mercury', 'https://mercury.com', '面向创业公司的美国数字银行与支付。',
           ('企业', '美国')),
        _s('Brex', 'https://www.brex.com', '创业公司商业账户与公司卡，融资友好。',
           ('企业', '美国')),
        _s('Alipay Global', 'https://www.alipay.com', '蚂蚁集团全球支付网络，服务商家跨境收款。',
           ('支付', '跨境')),
        _s('WeChat Pay Global', 'https://pay.weixin.qq.com', '微信支付跨境收款，服务海外商家。',
           ('支付', '跨境')),
        _s('Skrill', 'https://www.skrill.com', '电子钱包与跨境转账服务，支持多种货币。',
           ('钱包', '跨境')),
        _s('Neteller', 'https://www.neteller.com', '电子钱包，跨境转账与在线支付。',
           ('钱包', '跨境')),
        _s('PayPal Business', 'https://www.paypal.com', 'PayPal 企业账户，全球收款与结汇。',
           ('商户', '收款')),
        _s('2C2P', 'https://www.2c2p.com', '东南亚支付收单与多渠道支付解决方案。',
           ('东南亚', '收单')),
        _s('Adyen', 'https://www.adyen.com', '欧洲支付基础设施巨头，服务全球大型商户。',
           ('支付', '商户')),
        _s('Checkout.com', 'https://www.checkout.com', '企业级在线支付处理平台。',
           ('支付', '商户')),
        _s('Braintree', 'https://www.braintreepayments.com', 'PayPal 旗下开发者支付平台。',
           ('支付', '开发者')),
        _s('Plaid', 'https://plaid.com', '连接银行账户的 API 基础设施（支付与理财 App 用）。',
           ('api', '银行')),
        _s('Wise Platform', 'https://wise.com', 'Wise 跨境支付 API 与多币种钱包。',
           ('转账', 'api')),
        _s('Ripple', 'https://ripple.com', '基于 XRP 的企业跨境支付网络。',
           ('跨境', 'xrp')),
        _s('RippleX', 'https://ripplex.dev', 'Ripple 开发者平台与支付网络。',
           ('跨境', 'xrp')),
        _s('SWIFT', 'https://www.swift.com', '全球银行间报文传输系统（传统跨境汇款）。',
           ('跨境', 'swift')),
        _s('MoneyGram', 'https://www.moneygram.com', '全球汇款服务，覆盖大量国家。',
           ('汇款', '全球')),
        _s('Western Union', 'https://www.westernunion.com', '全球知名汇款与跨境转账服务。',
           ('汇款', '全球')),
        _s('WorldRemit', 'https://www.worldremit.com', '数字汇款平台，低手续费跨境转账。',
           ('汇款', '全球')),
        _s('TransferGo', 'https://www.transfergo.com', '欧洲低费用国际汇款。',
           ('汇款', '欧洲')),
        _s('Revolut Business', 'https://www.revolut.com', 'Revolut 企业账户与批量支付。',
           ('企业', '多币种')),
        _s('Stripe Connect', 'https://stripe.com/connect', 'Stripe 平台化分账与收款能力。',
           ('商户', '分账')),
        _s('Dlocal', 'https://www.dlocal.com', '拉美与新兴市场本地化收款解决方案。',
           ('新兴市场', '收单')),
        _s('Khipu', 'https://khipu.com', '拉美支付聚合平台。',
           ('拉美', '支付')),
        _s('Paddle', 'https://www.paddle.com', 'SaaS 电商的全球收款与税务处理平台。',
           ('saas', '收款')),
        _s('Lemonway', 'https://www.lemonway.com', '欧洲市场支付与资金托管解决方案。',
           ('欧洲', '支付')),
        _s('GoCardless', 'https://gocardless.com', '欧洲银行直接借记（Direct Debit）收款。',
           ('欧洲', '借记')),
        _s('Chargebee', 'https://www.chargebee.com', '订阅计费与收款的平台。',
           ('saas', '计费')),
        _s('Klarna Checkout', 'https://www.klarna.com', 'Klarna 先买后付与结算服务。',
           ('BNPL', '结算')),
        _s('Afterpay', 'https://www.afterpay.com', '全球 BNPL（先买后付）平台。',
           ('BNPL', '分期')),
    ],
}


class Command(BaseCommand):
    help = '创建演示分类与站点数据（幂等，约 300 个站点）'

    def handle(self, *args, **options):
        created_categories = 0
        for item in CATEGORIES:
            _, created = Category.objects.get_or_create(
                slug=item['slug'], defaults=item
            )
            created_categories += int(created)

        created_sites = 0
        updated_sites = 0
        per_category = []
        for slug, items in SITES_BY_CATEGORY.items():
            category = Category.objects.get(slug=slug)
            count = 0
            for idx, item in enumerate(items, start=1):
                site_data = {
                    k: v for k, v in {**item, 'sort_order': idx}.items()
                    if k != 'tags'
                }
                site, created = Site.objects.update_or_create(
                    name=item['name'], category=category, defaults=site_data
                )
                tag_objs = [
                    Tag.objects.get_or_create(name=t)[0] for t in item['tags']
                ]
                site.tags.set(tag_objs)
                created_sites += int(created)
                updated_sites += int(not created)
                count += 1
            per_category.append(f'{category.name} {count}')

        total_sites = sum(len(v) for v in SITES_BY_CATEGORY.values())
        self.stdout.write(
            self.style.SUCCESS(
                f'seed_demo 完成：分类 {len(CATEGORIES)} 个（新增 {created_categories}），'
                f'站点 {total_sites} 个（新增 {created_sites}，刷新 {updated_sites}）'
            )
        )
        self.stdout.write('各分类站点数：' + '、'.join(per_category))
